---
root: true
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - "@nuxtjs/eslint-config"
rules:
  comma-dangle:
    - error
    - only-multiline
  operator-linebreak:
    - error
    - before
  semi:
    - error
    - never
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  no-multi-spaces:
    - error
  no-multiple-empty-lines:
    - error
  keyword-spacing:
    - error
  arrow-spacing:
    - error
  object-curly-spacing:
    - error
    - always
  space-in-parens:
    - error
    - never